// Definición de tipos de acción
export const TYPES = {
  CREAR_TAREA: "ADD_TASK",
  SET_NEW_TASK: "SET_NEW_TASK",
  TOGGLE_TASK: "TOGGLE_TASK_COMPLETION",
  SET_DEFAULT_STATUS: "SET_DEFAULT_STATUS",
  DELETE_TASK: "DELETE_TASK",
};
